services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Backend\AvailioBundle\:
        resource: '../../*'
        exclude: '../../{Resources,DependencyInjection,Tests}'